#' @name 004_evaluation.R
#' @date 29.08.2025
#' @author Lisa Bald
#' @contact bald@staff.uni-marburg.de
#' 
#' @description
#' This script evaluates prediction maps for virtual species. 
#' Artificial maps are generated by combining the true species 
#' distributions with Gaussian random fields of varying spatial 
#' autocorrelation. For each species, several sampling strategies, 
#' test datasets, and replicates are evaluated. Evaluation metrics 
#' are calculated and saved.


# ================================================================
# 1. Load required packages
# ================================================================

library(dplyr)            # data manipulation
library(sf)               # spatial vector data
library(parallel)         # parallel processing
library(RandomFields)     # Gaussian random fields
library(NLMR)             # neutral landscape models
library(terra)            # raster handling
library(climateStability) # rescaling to [0,1]
library(RandomFieldsUtils)# dependency RandomField package
library(raster)           # dependency RandomField package

# ================================================================
# 2. Configure RandomFields settings
# ================================================================
RandomFields::RFoptions(cPrintlevel = 0,
                        spConform = FALSE,
                        install = "no",
                        seed = NULL)


# ================================================================
# 3. Set working directory and number of cores
# ================================================================

if (Sys.info()[[4]]=="PC19674") {
  setwd("M:/user/bald/SDM/sdmPerformance/")
  nCores=1
} else if (Sys.info()[[4]]=="pc19543") {
  nCores=1
}

# # Unique identifier for this specific configuration (called: run)
nameRun <- paste0("run", 12)

# ================================================================
# 4. Define experimental evaluation setup
# ================================================================

if(!file.exists(paste0("data/",nameRun,"/maps_cor.RDS"))){
  df=expand.grid(size=as.character(c("KNNDM","random","block1","block2","clusters")) , # data separation strategies
                 species=c("VS01", "VS02", "VS03", "VS04", "VS05", "VS06", "VS07", "VS08", "VS09", "VS10"), # virtual species IDs
                 points=unique(sapply(strsplit(gsub(".gpkg", "", 
                                                    list.files("data/run2/virtualSpeciesTrain", 
                                                               full.names = FALSE,pattern=".gpkg")), "_"), `[`, 2)), # number of originally sampled points points
                 replicates=1:5, # replicate runs
                 model=as.character(c("NA")), # placeholder (no models trained here)
                 testData = 1:6            ) # test dataset identifiers
  

  
  df$goodnessOfFit <- sample(seq(0,1,0.01),nrow(df), replace=T)
  plot(table(df$goodnessOfFit))
  df=df %>% arrange(goodnessOfFit)
  rownames(df) <- 1:nrow(df)
  saveRDS(df, paste0("data/",nameRun,"/maps_cor.RDS"))
} else df=readRDS(paste0("data/",nameRun,"/maps_cor.RDS"))
plot(table(df$goodnessOfFit))

# ================================================================
# 5. Model evaluation
# ================================================================

vars_path=normalizePath("data/variables.tif")
source(paste0("R/",nameRun,"/functions/performanceEstimation.R"))


mclapply(1:nrow(df), function(i){
  
  print(i)
  
  vars=terra::rast(vars_path)
  vs=sf::read_sf(paste0("data/run2/virtualSpeciesTrain/",as.character(df$species[i]),"_",as.character(df$points[i]),"_",df$replicates[i],".gpkg"))
  # Select test data according to sampling strategy
  test <- vs %>%
    dplyr::filter(.data[[as.character(df$size[i])]] == df$testData[i])
  
  # Abort if fewer than 5 presence points available
  if(nrow(test%>%dplyr::filter(Real==1))<2) return(NULL)
  
  # Load true species distribution raster
  realDistribution=terra::rast(paste0("data/virtualSpecies/",as.character(df$species[i]),".tif"))
  
  # ================================================================
  # 5a. Generate artificial prediction maps with spatial autocorrelation (cannot be run in parallel)
  # ================================================================
  
  # create gaussian random fields and merge with the real distribution
  if(!file.exists(paste0("data/run12/maps/",as.character(df$species[i]),"_",df$size[i],"_",df$model[i],"_testData",df$testData[i],"_points",as.character(df$points[i]),"_replicates",df$replicates[i],".tif"))){
    if(!dir.exists(paste0("data/run12/maps"))) dir.create(paste0("data/run12/maps"),recursive=T)
    
    # Simulate Gaussian random field (spatial autocorrelation range sampled randomly)
    autocorrRange=sample(c(20,50,100,500,800),size=1)
    randomField=nlm_gaussianfield(nrow=1777, ncol=2247, resolution=813.3488,
                                  autocorr_range = autocorrRange)
    
    # Convert to terra raster and align with true distribution
    randomField=terra::rast(randomField)
    terra::ext(randomField) <- terra::ext(realDistribution)
    terra::crs(randomField)<- terra::crs(realDistribution)
    randomField=terra::mask(randomField, realDistribution)
    
    # Combine random field with true distribution (weighted mixture)
    randomEffects <-df$goodnessOfFit[i]
    x1 <-( randomEffects * realDistribution)
    x2 <- ((1-randomEffects) * randomField)
    pred <- x1 + x2
    trueCor <- terra::layerCor(terra::rast(list(pred,realDistribution)),fun="cor")$correlation[[1,2]]
    
    if(randomEffects != 0){
      if (round(abs(trueCor-randomEffects),2) >= 0.02){
        x=1
        y=1
        if(trueCor > randomEffects){
          while(round(abs(trueCor-randomEffects),2) >= 0.02){
            x1 <-( randomEffects * realDistribution *y)
            x2 <- ((1-randomEffects) * randomField *x)
            pred <- x1 + x2
            trueCor <- terra::layerCor(terra::rast(list(pred,realDistribution)),fun="cor")$correlation[[1,2]]
            x <- x+0.01
            y <- y-0.01
            print(trueCor)
            if(trueCor < 0) break
          }
        }
        if(trueCor < randomEffects){
          while(round(abs(trueCor-randomEffects),2) <= 0.02){
            x1 <-( randomEffects * realDistribution *y)
            x2 <- ((1-randomEffects) * randomField *x)
            pred <- x1 + x2
            trueCor <- terra::layerCor(terra::rast(list(pred,realDistribution)),fun="cor")$correlation[[1,2]]
            x <- x-0.01
            y <- y+0.01
            print(trueCor)
            if(trueCor < 0) break
          }
        }
      }
    }
    print(paste("Random effect is:",randomEffects,". Correlation is:", round(trueCor,2)))
    
    
    pred=climateStability::rescale0to1(pred) # normalize to [0,1]
    terra::writeRaster(pred, paste0("data/run12/maps/",as.character(df$species[i]),"_",df$size[i],"_",df$model[i],"_testData",df$testData[i],"_points",as.character(df$points[i]),"_replicates",df$replicates[i],".tif"))
  } else pred=terra::rast(paste0("data/run12/maps/",as.character(df$species[i]),"_",df$size[i],"_",df$model[i],"_testData",df$testData[i],"_points",as.character(df$points[i]),"_replicates",df$replicates[i],".tif"))
  
},mc.cores=nCores)


